import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/modules/nav/Navbar";
import ScrollOne from "@/modules/scroll-one/ScrollOne";
import ScrollTwo from "@/modules/scroll-two/ScrollTwo";
import ScrollThree from "@/modules/scroll-three/ScrollThree";
import ScrollFour from "@/modules/scroll-four/ScrollFour";
import Team from "@/modules/team/Team";
import Footer from "@/modules/footer/Footer";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "6rem",
          minHeight: "100vh",
        }}
      >
        <ScrollOne />
        <ScrollTwo />
        <ScrollThree />
        <ScrollFour />
        <Team />
        <Footer />
      </Box>
    </>
  );
}
